/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerMusica;

/**
 *
 * @author Elizabeth
 */
public class TelaPrincipalFrame extends javax.swing.JFrame {
private ControllerMusica controllerMusica;
    /**
     * Creates new form TelaPrincipalFrame
     */

    public TelaPrincipalFrame() {
        initComponents();
        controllerMusica = new ControllerMusica(this);
        
    }
    
    
    
    public BuscarMusicasFrame criarBuscarMusicasFrame(ControllerMusica controller) {
        return new BuscarMusicasFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bt_ir_curtidas = new javax.swing.JButton();
        bt_ir_descurtidas = new javax.swing.JButton();
        bt_ir_buscar_musicas = new javax.swing.JButton();
        bt_ir_playlists = new javax.swing.JButton();
        lbl_texto_principal = new javax.swing.JLabel();
        lbl_text_spotifei = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_ir_curtidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_ir_curtidas.setText("Músicas curtidas");
        bt_ir_curtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ir_curtidasActionPerformed(evt);
            }
        });

        bt_ir_descurtidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_ir_descurtidas.setText("Músicas descurtidas");
        bt_ir_descurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ir_descurtidasActionPerformed(evt);
            }
        });

        bt_ir_buscar_musicas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_ir_buscar_musicas.setText("Buscar músicas");
        bt_ir_buscar_musicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ir_buscar_musicasActionPerformed(evt);
            }
        });

        bt_ir_playlists.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_ir_playlists.setText("Playlists");
        bt_ir_playlists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ir_playlistsActionPerformed(evt);
            }
        });

        lbl_texto_principal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_texto_principal.setText("Que bom te ver novamente!");

        lbl_text_spotifei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_text_spotifei.setText("SpotiFei");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lbl_text_spotifei))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lbl_texto_principal)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_ir_descurtidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(bt_ir_buscar_musicas)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(bt_ir_curtidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_ir_playlists)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_text_spotifei)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_texto_principal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_ir_playlists, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_ir_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ir_buscar_musicas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ir_descurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>                        

    private void bt_ir_curtidasActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void bt_ir_descurtidasActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void bt_ir_buscar_musicasActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    BuscarMusicasFrame buscarMusicasFrame = new BuscarMusicasFrame(); // Crie a view primeiro
    ControllerMusica controllerMusica = new ControllerMusica(buscarMusicasFrame); // Crie o controller associado à view
    buscarMusicasFrame.setControllerMusica(controllerMusica); // Associe o controller à view (se necessário)
    buscarMusicasFrame.setVisible(true);
    }                                                    

    private void bt_ir_playlistsActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        PlaylistFrame playlistFrame = new PlaylistFrame(); // Cria a tela de playlists
        playlistFrame.setVisible(true); // Torna visível

    }                                               

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     //   try {
       //     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
         //       if ("Nimbus".equals(info.getName())) {
           //         javax.swing.UIManager.setLookAndFeel(info.getClassName());
             //       break;
//               // }
  //          }
    //    } catch (ClassNotFoundException ex) {
      //      java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //} catch (InstantiationException ex) {
          //  java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  //      } catch (IllegalAccessException ex) {
    //        java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      //  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //    java.util.logging.Logger.getLogger(TelaPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //}
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
           // public void run() {
          //      new TelaPrincipalFrame().setVisible(true);
        //    }
      //  });
    //}

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_ir_buscar_musicas;
    private javax.swing.JButton bt_ir_curtidas;
    private javax.swing.JButton bt_ir_descurtidas;
    private javax.swing.JButton bt_ir_playlists;
    private javax.swing.JLabel lbl_text_spotifei;
    private javax.swing.JLabel lbl_texto_principal;
    // End of variables declaration                   
}
